import type { AdminLang } from "@/lib/admin-i18n";
import type { PresetId } from "./types";

export const editorCopy = {
  de: {
    title: "Bild bearbeiten",
    close: "Schließen",
    loading: "Bild wird geladen…",
    loadError: "Dieses Bild konnte nicht geladen werden.",
    tabAi: "KI",
    tabAdjust: "Anpassen",
    tabCrop: "Zuschnitt",
    removeBg: "Hintergrund entfernen",
    restoreBg: "Freisteller zurücksetzen",
    autoEnhance: "Auto-Enhance / KI-Optimierung",
    bgLabel: "Ausgabehintergrund",
    bgWhite: "Reinweiß",
    bgTransparent: "Transparent",
    bgHint:
      "Der Freisteller erkennt das Produkt und macht den Hintergrund transparent. Die Kanten des Produkts bleiben erhalten.",
    lightLabel: "Licht & Belichtung",
    colorLabel: "Farbe & Temperatur",
    qualityLabel: "Schärfe & Qualität",
    brightness: "Helligkeit",
    contrast: "Kontrast",
    highlights: "Glanzlichter",
    shadows: "Schatten",
    whites: "Weißer Bereich",
    blacks: "Schwarzer Bereich",
    hue: "Farbton",
    temperature: "Farbtemperatur",
    vibrance: "Lebendigkeit",
    saturation: "Sättigung",
    sharpness: "Schärfe",
    noiseReduction: "Störungsreduzierung",
    resetAdjustments: "Anpassungen zurücksetzen",
    presets: "Filter",
    cropFree: "Freiform",
    cropSquare: "Quadrat (1:1)",
    cropWide: "16:9",
    cropClassic: "4:3",
    cropOriginal: "Original",
    flipH: "Horizontal spiegeln",
    flipV: "Vertikal spiegeln",
    rotate: "90° drehen",
    outputHint: "Ausgabe immer 1400×1400",
    cancel: "Abbrechen",
    apply: "Übernehmen & hochladen",
    applying: "Exportiere…",
    step: "Bild",
    bgError: "Hintergrund konnte nicht entfernt werden. Bitte erneut versuchen.",
    unsupported: "Dieses Bildformat wird nicht unterstützt.",
    editHint:
      "Nach der Auswahl öffnet sich der Bildeditor. Ein Klick auf ein vorhandenes Bild bearbeitet es erneut. Stern = Hauptbild.",
    choose: "Bild wählen & bearbeiten",
    cover: "Cover",
    remove: "Bild entfernen",
    setCover: "Als Hauptbild festlegen",
  },
  ar: {
    title: "تعديل الصورة",
    close: "إغلاق",
    loading: "جارٍ تحميل الصورة…",
    loadError: "تعذر تحميل هذه الصورة.",
    tabAi: "ذكاء",
    tabAdjust: "ضبط",
    tabCrop: "قص",
    removeBg: "إزالة الخلفية",
    restoreBg: "التراجع عن الإزالة",
    autoEnhance: "تحسين تلقائي / تحسين بالذكاء",
    bgLabel: "خلفية التصدير",
    bgWhite: "أبيض",
    bgTransparent: "شفاف",
    bgHint: "تتعرّف الأداة على المنتج وتجعل الخلفية شفافة مع الإبقاء على حواف المنتج.",
    lightLabel: "الضوء والتعريض",
    colorLabel: "اللون والحرارة",
    qualityLabel: "الحدة والجودة",
    brightness: "السطوع",
    contrast: "التباين",
    highlights: "الإضاءات",
    shadows: "الظلال",
    whites: "المناطق البيضاء",
    blacks: "المناطق السوداء",
    hue: "درجة اللون",
    temperature: "حرارة اللون",
    vibrance: "الحيوية",
    saturation: "التشبع",
    sharpness: "الحدة",
    noiseReduction: "تقليل التشويش",
    resetAdjustments: "إعادة ضبط التعديلات",
    presets: "فلاتر",
    cropFree: "حر",
    cropSquare: "مربع (1:1)",
    cropWide: "16:9",
    cropClassic: "4:3",
    cropOriginal: "الأصل",
    flipH: "قلب أفقي",
    flipV: "قلب عمودي",
    rotate: "تدوير 90°",
    outputHint: "التصدير دائماً 1400×1400",
    cancel: "إلغاء",
    apply: "اعتماد ورفع",
    applying: "جارٍ التصدير…",
    step: "صورة",
    bgError: "تعذر إزالة الخلفية. حاول مرة أخرى.",
    unsupported: "صيغة الصورة غير مدعومة.",
    editHint: "بعد الاختيار يفتح محرر الصور. النقر على صورة موجودة يعيد تحريرها. النجمة = الصورة الرئيسية.",
    choose: "اختيار صورة وتعديلها",
    cover: "الغلاف",
    remove: "حذف الصورة",
    setCover: "تعيين كصورة رئيسية",
  },
} as const;

export type EditorCopy = {
  [K in keyof (typeof editorCopy)["de"]]: string;
};

export function copyFor(lang: AdminLang): EditorCopy {
  return editorCopy[lang];
}

export const PRESET_LABELS: Record<AdminLang, Record<PresetId, string>> = {
  de: {
    original: "Original",
    strahlend: "Strahlend",
    dramatisch: "Dramatisch",
    strahlendKalt: "Strahlend Kalt",
    strahlendWarm: "Strahlend Warm",
  },
  ar: {
    original: "الأصل",
    strahlend: "ساطع",
    dramatisch: "درامي",
    strahlendKalt: "ساطع بارد",
    strahlendWarm: "ساطع دافئ",
  },
};
