#!/usr/bin/env bash
# Per-boot startup: bring up the Docker daemon and the local Supabase stack,
# then write .env.local so the Next.js app can talk to it.
# Safe to run repeatedly.
set -euo pipefail

cd "$(dirname "$0")/.."

# --- Docker daemon -----------------------------------------------------------
# Nested containers need the legacy iptables backend and the fuse-overlayfs
# storage driver for the daemon to run and for container networking to work.
if ! docker info >/dev/null 2>&1; then
  echo "[start] Configuring and starting dockerd..."
  sudo update-alternatives --set iptables /usr/sbin/iptables-legacy >/dev/null 2>&1 || true
  sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy >/dev/null 2>&1 || true
  sudo mkdir -p /etc/docker
  echo '{ "storage-driver": "fuse-overlayfs" }' | sudo tee /etc/docker/daemon.json >/dev/null
  # Log to a root-owned path and clear any stale log so the redirect never hits
  # a permission error on a file owned by another user (e.g. captured in a snapshot).
  sudo bash -c 'rm -f /var/log/jmle-dockerd.log; nohup dockerd >/var/log/jmle-dockerd.log 2>&1 &'
  for _ in $(seq 1 60); do
    if sudo docker info >/dev/null 2>&1; then break; fi
    sleep 1
  done
fi
# Let the ubuntu user reach the daemon without sudo.
sudo chmod 666 /var/run/docker.sock 2>/dev/null || true

# --- Supabase local stack ----------------------------------------------------
echo "[start] Starting Supabase (applies migrations + seed on first run)..."
supabase start

# --- Environment file for Next.js -------------------------------------------
echo "[start] Writing .env.local from supabase status..."
eval "$(supabase status -o env 2>/dev/null)"
cat > .env.local <<EOF
# Auto-generated by scripts/cloud-agent-start.sh — points at the local Supabase stack.
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

# Stripe — placeholder test keys (replace with real test keys to exercise checkout)
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_placeholder
STRIPE_SECRET_KEY=sk_test_placeholder
STRIPE_WEBHOOK_SECRET=whsec_placeholder

# App
NEXT_PUBLIC_APP_URL=http://localhost:3000
EOF

echo "[start] Supabase Studio: ${STUDIO_URL}"
echo "[start] Ready. Start the app with: npm run dev"
