-- Production brand catalog reset: exactly 71 brands + robust product rematch
-- Re-runnable. Preferred TS path: PRODUCTION_SUPABASE_* + scripts/reset-brands.ts --production
BEGIN;
UPDATE public.products SET brand_id = NULL WHERE brand_id IS NOT NULL;
DELETE FROM public.brand_logos;
INSERT INTO public.brand_logos (id, name, image, link_url, sort_order, active) VALUES
  ('brand-aldurra', 'الدرة', '/placeholder.svg', NULL, 1, true),
  ('brand-shamsin', 'شمسين', '/placeholder.svg', NULL, 2, true),
  ('brand-domo', 'دومو', '/placeholder.svg', NULL, 3, true),
  ('brand-derby', 'ديربي', '/placeholder.svg', NULL, 4, true),
  ('brand-snickers', 'سنيكرز', '/placeholder.svg', NULL, 5, true),
  ('brand-lina', 'لينا', '/placeholder.svg', NULL, 6, true),
  ('brand-golden-touch', 'غولدن تاتش', '/placeholder.svg', NULL, 7, true),
  ('brand-shockx', 'شوكس', '/placeholder.svg', NULL, 8, true),
  ('brand-laziza', 'لذيذة', '/placeholder.svg', NULL, 9, true),
  ('brand-rani', 'راني', '/placeholder.svg', NULL, 10, true),
  ('brand-mine-tea', 'ماين تي', '/placeholder.svg', NULL, 11, true),
  ('brand-dana', 'دانا', '/placeholder.svg', NULL, 12, true),
  ('brand-lara', 'لارا', '/placeholder.svg', NULL, 13, true),
  ('brand-laughing-cow', 'جبنة البقرة الضاحكة', '/placeholder.svg', NULL, 14, true),
  ('brand-kiri', 'كيري', '/placeholder.svg', NULL, 15, true),
  ('brand-al-rai', 'الراعي', '/placeholder.svg', NULL, 16, true),
  ('brand-hajdu', 'هاجدو', '/placeholder.svg', NULL, 17, true),
  ('brand-al-mukhtar', 'المختار', '/placeholder.svg', NULL, 18, true),
  ('brand-puck', 'بوك', '/placeholder.svg', NULL, 19, true),
  ('brand-altonsa', 'ألتونسا', '/placeholder.svg', NULL, 20, true),
  ('brand-sunquick', 'سنكويك', '/placeholder.svg', NULL, 21, true),
  ('brand-al-arjawi', 'العرجاوي', '/placeholder.svg', NULL, 22, true),
  ('brand-vimto', 'فيمتو', '/placeholder.svg', NULL, 23, true),
  ('brand-morecorno', 'موركورنو', '/placeholder.svg', NULL, 24, true),
  ('brand-keraza', 'كرزة', '/placeholder.svg', NULL, 25, true),
  ('brand-mahmoud', 'محمود', '/placeholder.svg', NULL, 26, true),
  ('brand-ahmad', 'أحمد', '/placeholder.svg', NULL, 27, true),
  ('brand-do-ghazal', 'دو غزال', '/placeholder.svg', NULL, 28, true),
  ('brand-barbican', 'بابريكان', '/placeholder.svg', NULL, 29, true),
  ('brand-al-fakher', 'الفاخر', '/placeholder.svg', NULL, 30, true),
  ('brand-maza', 'مازا', '/placeholder.svg', NULL, 31, true),
  ('brand-hamoul', 'هامول', '/placeholder.svg', NULL, 32, true),
  ('brand-al-emlaq', 'العملاق', '/placeholder.svg', NULL, 33, true),
  ('brand-bin-al-hamwi', 'بن الحموي', '/placeholder.svg', NULL, 34, true),
  ('brand-al-kaseeh', 'الكسيح', '/placeholder.svg', NULL, 35, true),
  ('brand-somar', 'سومار', '/placeholder.svg', NULL, 36, true),
  ('brand-bin-al-shami', 'بن الشامي', '/placeholder.svg', NULL, 37, true),
  ('brand-aramis', 'أراميس', '/placeholder.svg', NULL, 38, true),
  ('brand-amarin', 'أمارين', '/placeholder.svg', NULL, 39, true),
  ('brand-doctor-chef', 'دكتور شيف', '/placeholder.svg', NULL, 40, true),
  ('brand-sweet-hammoud', 'سويت حمود', '/placeholder.svg', NULL, 41, true),
  ('brand-qualiko', 'كواليكو', '/placeholder.svg', NULL, 42, true),
  ('brand-hamada', 'حمادة', '/placeholder.svg', NULL, 43, true),
  ('brand-dimo', 'ديمو', '/placeholder.svg', NULL, 44, true),
  ('brand-al-ghouta', 'الغوطة', '/placeholder.svg', NULL, 45, true),
  ('brand-yagouri', 'ياقوري', '/placeholder.svg', NULL, 46, true),
  ('brand-leyland', 'لايلاند', '/placeholder.svg', NULL, 47, true),
  ('brand-city-cafe', 'سيتي كافيه', '/placeholder.svg', NULL, 48, true),
  ('brand-najjar', 'نجار', '/placeholder.svg', NULL, 49, true),
  ('brand-bin-al-haseeb', 'بن الحسيب', '/placeholder.svg', NULL, 50, true),
  ('brand-sheikh-al-kar', 'شيخ الكار', '/placeholder.svg', NULL, 51, true),
  ('brand-kharta', 'خارطة', '/placeholder.svg', NULL, 52, true),
  ('brand-pepori', 'بيبوري', '/placeholder.svg', NULL, 53, true),
  ('brand-zwan', 'زوان', '/placeholder.svg', NULL, 54, true),
  ('brand-tosca', 'توسكا', '/placeholder.svg', NULL, 55, true),
  ('brand-kalbahar', 'كلبهار', '/placeholder.svg', NULL, 56, true),
  ('brand-bulbul', 'بلبل', '/placeholder.svg', NULL, 57, true),
  ('brand-wazza-rice', 'أرز الوزة', '/placeholder.svg', NULL, 58, true),
  ('brand-abu-kas', 'أبو كاس', '/placeholder.svg', NULL, 59, true),
  ('brand-shahia', 'شهية', '/placeholder.svg', NULL, 60, true),
  ('brand-alaska', 'الاسكا', '/placeholder.svg', NULL, 61, true),
  ('brand-blue-mill', 'بلو ميل', '/placeholder.svg', NULL, 62, true),
  ('brand-hana', 'هنا', '/placeholder.svg', NULL, 63, true),
  ('brand-al-ameera', 'الأميرة', '/placeholder.svg', NULL, 64, true),
  ('brand-nabali', 'نبالي', '/placeholder.svg', NULL, 65, true),
  ('brand-afamia-al-sham', 'افاميا الشام', '/placeholder.svg', NULL, 66, true),
  ('brand-chtoura-garden', 'حدائق شتورة', '/placeholder.svg', NULL, 67, true),
  ('brand-freshly', 'فرشلي', '/placeholder.svg', NULL, 68, true),
  ('brand-nestle', 'نسلة', '/placeholder.svg', NULL, 69, true),
  ('brand-rana', 'رنا', '/placeholder.svg', NULL, 70, true),
  ('brand-indomie', 'إندومي', '/placeholder.svg', NULL, 71, true);
UPDATE public.products SET brand_id = 'brand-laughing-cow' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%جبنة البقرة الضاحكة%');
UPDATE public.products SET brand_id = 'brand-laughing-cow' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mThe Laughing Cow\M');
UPDATE public.products SET brand_id = 'brand-laughing-cow' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mLa Vache Qui Rit\M');
UPDATE public.products SET brand_id = 'brand-chtoura-garden' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mChtoura Gardens\M');
UPDATE public.products SET brand_id = 'brand-afamia-al-sham' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAfamia Al Sham\M');
UPDATE public.products SET brand_id = 'brand-chtoura-garden' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mChtoura Garden\M');
UPDATE public.products SET brand_id = 'brand-laughing-cow' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mVache Qui Rit\M');
UPDATE public.products SET brand_id = 'brand-sweet-hammoud' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mSweet Hammoud\M');
UPDATE public.products SET brand_id = 'brand-bin-al-haseeb' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mBin Al Haseeb\M');
UPDATE public.products SET brand_id = 'brand-sheikh-al-kar' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mSheikh Al Kar\M');
UPDATE public.products SET brand_id = 'brand-sheikh-al-kar' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mSheikh Alkaar\M');
UPDATE public.products SET brand_id = 'brand-chtoura-garden' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mChtouraGarden\M');
UPDATE public.products SET brand_id = 'brand-golden-touch' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mGolden Touch\M');
UPDATE public.products SET brand_id = 'brand-laughing-cow' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mLaughing Cow\M');
UPDATE public.products SET brand_id = 'brand-bin-al-hamwi' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mBin Al Hamwi\M');
UPDATE public.products SET brand_id = 'brand-bin-al-shami' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mBin Al Shami\M');
UPDATE public.products SET brand_id = 'brand-sweet-hammoud' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mSweet Hamoud\M');
UPDATE public.products SET brand_id = 'brand-sweet-hammoud' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mSweethammoud\M');
UPDATE public.products SET brand_id = 'brand-sheikh-al-kar' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mSheik Al Kar\M');
UPDATE public.products SET brand_id = 'brand-afamia-al-sham' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%افاميا الشام%');
UPDATE public.products SET brand_id = 'brand-golden-touch' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mGoldentouch\M');
UPDATE public.products SET brand_id = 'brand-doctor-chef' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mDoctor Chef\M');
UPDATE public.products SET brand_id = 'brand-afamia-al-sham' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAfamia Sham\M');
UPDATE public.products SET brand_id = 'brand-chtoura-garden' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%حدائق شتورة%');
UPDATE public.products SET brand_id = 'brand-golden-touch' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%غولدن تاتش%');
UPDATE public.products SET brand_id = 'brand-al-mukhtar' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl Mukhtar\M');
UPDATE public.products SET brand_id = 'brand-al-mukhtar' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl-Mukhtar\M');
UPDATE public.products SET brand_id = 'brand-city-cafe' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%سيتي كافيه%');
UPDATE public.products SET brand_id = 'brand-wazza-rice' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mWazza Rice\M');
UPDATE public.products SET brand_id = 'brand-al-mukhtar' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAlmukhtar\M');
UPDATE public.products SET brand_id = 'brand-sunquick' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mSun Quick\M');
UPDATE public.products SET brand_id = 'brand-sunquick' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mSun-Quick\M');
UPDATE public.products SET brand_id = 'brand-al-arjawi' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl Arjawi\M');
UPDATE public.products SET brand_id = 'brand-al-arjawi' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl-Arjawi\M');
UPDATE public.products SET brand_id = 'brand-morecorno' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mMorecorno\M');
UPDATE public.products SET brand_id = 'brand-do-ghazal' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mDo Ghazal\M');
UPDATE public.products SET brand_id = 'brand-do-ghazal' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mDo-Ghazal\M');
UPDATE public.products SET brand_id = 'brand-al-fakher' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl Fakher\M');
UPDATE public.products SET brand_id = 'brand-al-fakher' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl-Fakher\M');
UPDATE public.products SET brand_id = 'brand-bin-al-hamwi' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%بن الحموي%');
UPDATE public.products SET brand_id = 'brand-al-kaseeh' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl Kaseeh\M');
UPDATE public.products SET brand_id = 'brand-al-kaseeh' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl-Kaseeh\M');
UPDATE public.products SET brand_id = 'brand-bin-al-shami' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%بن الشامي%');
UPDATE public.products SET brand_id = 'brand-doctor-chef' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%دكتور شيف%');
UPDATE public.products SET brand_id = 'brand-sweet-hammoud' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%سويت حمود%');
UPDATE public.products SET brand_id = 'brand-al-ghouta' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl Ghouta\M');
UPDATE public.products SET brand_id = 'brand-al-ghouta' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl-Ghouta\M');
UPDATE public.products SET brand_id = 'brand-city-cafe' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mCity Cafe\M');
UPDATE public.products SET brand_id = 'brand-city-cafe' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mCity Café\M');
UPDATE public.products SET brand_id = 'brand-bin-al-haseeb' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%بن الحسيب%');
UPDATE public.products SET brand_id = 'brand-bin-al-haseeb' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl Haseeb\M');
UPDATE public.products SET brand_id = 'brand-sheikh-al-kar' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%شيخ الكار%');
UPDATE public.products SET brand_id = 'brand-wazza-rice' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%أرز الوزة%');
UPDATE public.products SET brand_id = 'brand-blue-mill' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mBlue Mill\M');
UPDATE public.products SET brand_id = 'brand-al-ameera' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl Ameera\M');
UPDATE public.products SET brand_id = 'brand-al-ameera' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl-Ameera\M');
UPDATE public.products SET brand_id = 'brand-aldurra' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl Durra\M');
UPDATE public.products SET brand_id = 'brand-aldurra' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl-Durra\M');
UPDATE public.products SET brand_id = 'brand-aldurra' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mEl Durra\M');
UPDATE public.products SET brand_id = 'brand-shamsin' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mChamsine\M');
UPDATE public.products SET brand_id = 'brand-shamsin' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mShamseen\M');
UPDATE public.products SET brand_id = 'brand-snickers' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mSnickers\M');
UPDATE public.products SET brand_id = 'brand-mine-tea' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mMine Tea\M');
UPDATE public.products SET brand_id = 'brand-altonsa' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl Tonsa\M');
UPDATE public.products SET brand_id = 'brand-sunquick' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mSunqueak\M');
UPDATE public.products SET brand_id = 'brand-sunquick' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mSunquick\M');
UPDATE public.products SET brand_id = 'brand-al-arjawi' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%العرجاوي%');
UPDATE public.products SET brand_id = 'brand-morecorno' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%موركورنو%');
UPDATE public.products SET brand_id = 'brand-morecorno' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mMorcorno\M');
UPDATE public.products SET brand_id = 'brand-do-ghazal' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mDoghazal\M');
UPDATE public.products SET brand_id = 'brand-barbican' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%بابريكان%');
UPDATE public.products SET brand_id = 'brand-barbican' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%باربيكان%');
UPDATE public.products SET brand_id = 'brand-barbican' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mBarbican\M');
UPDATE public.products SET brand_id = 'brand-al-fakher' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAlfakher\M');
UPDATE public.products SET brand_id = 'brand-al-emlaq' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl Emlaq\M');
UPDATE public.products SET brand_id = 'brand-al-emlaq' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl-Emlaq\M');
UPDATE public.products SET brand_id = 'brand-bin-al-hamwi' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl Hamwi\M');
UPDATE public.products SET brand_id = 'brand-al-kaseeh' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAlkaseeh\M');
UPDATE public.products SET brand_id = 'brand-bin-al-shami' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl Shami\M');
UPDATE public.products SET brand_id = 'brand-al-ghouta' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAlghouta\M');
UPDATE public.products SET brand_id = 'brand-city-cafe' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mCityCafe\M');
UPDATE public.products SET brand_id = 'brand-bin-al-haseeb' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAlhaseeb\M');
UPDATE public.products SET brand_id = 'brand-kalbahar' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mKalbahar\M');
UPDATE public.products SET brand_id = 'brand-kalbahar' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mKolbahar\M');
UPDATE public.products SET brand_id = 'brand-wazza-rice' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl Wazza\M');
UPDATE public.products SET brand_id = 'brand-abu-kas' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAbu Cass\M');
UPDATE public.products SET brand_id = 'brand-abu-kas' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAbou Kas\M');
UPDATE public.products SET brand_id = 'brand-blue-mill' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mBluemill\M');
UPDATE public.products SET brand_id = 'brand-al-ameera' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mPrincess\M');
UPDATE public.products SET brand_id = 'brand-al-ameera' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAlameera\M');
UPDATE public.products SET brand_id = 'brand-freshly' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mFreshley\M');
UPDATE public.products SET brand_id = 'brand-indomie' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mIndo Mie\M');
UPDATE public.products SET brand_id = 'brand-aldurra' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mEldurra\M');
UPDATE public.products SET brand_id = 'brand-aldurra' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAlDurra\M');
UPDATE public.products SET brand_id = 'brand-shamsin' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mShamsin\M');
UPDATE public.products SET brand_id = 'brand-shamsin' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mChamsin\M');
UPDATE public.products SET brand_id = 'brand-laziza' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mLazeeza\M');
UPDATE public.products SET brand_id = 'brand-mine-tea' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%ماين تي%');
UPDATE public.products SET brand_id = 'brand-al-mukhtar' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%المختار%');
UPDATE public.products SET brand_id = 'brand-altonsa' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%ألتونسا%');
UPDATE public.products SET brand_id = 'brand-altonsa' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAltonsa\M');
UPDATE public.products SET brand_id = 'brand-mahmoud' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mMahmoud\M');
UPDATE public.products SET brand_id = 'brand-mahmoud' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mMahmood\M');
UPDATE public.products SET brand_id = 'brand-do-ghazal' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%دو غزال%');
UPDATE public.products SET brand_id = 'brand-hamoul' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mHammoul\M');
UPDATE public.products SET brand_id = 'brand-al-emlaq' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%العملاق%');
UPDATE public.products SET brand_id = 'brand-al-emlaq' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAlemlaq\M');
UPDATE public.products SET brand_id = 'brand-bin-al-hamwi' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAlhamwi\M');
UPDATE public.products SET brand_id = 'brand-bin-al-shami' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAlshami\M');
UPDATE public.products SET brand_id = 'brand-doctor-chef' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mDr Chef\M');
UPDATE public.products SET brand_id = 'brand-doctor-chef' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mDr\. Chef\M');
UPDATE public.products SET brand_id = 'brand-qualiko' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%كواليكو%');
UPDATE public.products SET brand_id = 'brand-qualiko' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mQualiko\M');
UPDATE public.products SET brand_id = 'brand-qualiko' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mQualico\M');
UPDATE public.products SET brand_id = 'brand-hamada' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mHammada\M');
UPDATE public.products SET brand_id = 'brand-yagouri' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mYagouri\M');
UPDATE public.products SET brand_id = 'brand-yagouri' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mYaqouri\M');
UPDATE public.products SET brand_id = 'brand-leyland' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%لايلاند%');
UPDATE public.products SET brand_id = 'brand-leyland' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mLeyland\M');
UPDATE public.products SET brand_id = 'brand-leyland' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mLayland\M');
UPDATE public.products SET brand_id = 'brand-kharta' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mKharita\M');
UPDATE public.products SET brand_id = 'brand-wazza-rice' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAlwazza\M');
UPDATE public.products SET brand_id = 'brand-abu-kas' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%أبو كاس%');
UPDATE public.products SET brand_id = 'brand-abu-kas' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAbu Kas\M');
UPDATE public.products SET brand_id = 'brand-shahia' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mShaheya\M');
UPDATE public.products SET brand_id = 'brand-blue-mill' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%بلو ميل%');
UPDATE public.products SET brand_id = 'brand-al-ameera' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%الأميرة%');
UPDATE public.products SET brand_id = 'brand-chtoura-garden' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mShtoura\M');
UPDATE public.products SET brand_id = 'brand-chtoura-garden' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mChtoura\M');
UPDATE public.products SET brand_id = 'brand-chtoura-garden' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mChatura\M');
UPDATE public.products SET brand_id = 'brand-freshly' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mFreshly\M');
UPDATE public.products SET brand_id = 'brand-freshly' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mFreshli\M');
UPDATE public.products SET brand_id = 'brand-indomie' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mIndomie\M');
UPDATE public.products SET brand_id = 'brand-snickers' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%سنيكرز%');
UPDATE public.products SET brand_id = 'brand-shockx' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mShockx\M');
UPDATE public.products SET brand_id = 'brand-shockx' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mShocks\M');
UPDATE public.products SET brand_id = 'brand-shockx' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mChocoX\M');
UPDATE public.products SET brand_id = 'brand-laziza' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mLaziza\M');
UPDATE public.products SET brand_id = 'brand-laziza' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mLazeza\M');
UPDATE public.products SET brand_id = 'brand-mine-tea' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mMy Tea\M');
UPDATE public.products SET brand_id = 'brand-mine-tea' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mMinTea\M');
UPDATE public.products SET brand_id = 'brand-al-rai' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%الراعي%');
UPDATE public.products SET brand_id = 'brand-al-rai' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl Rai\M');
UPDATE public.products SET brand_id = 'brand-al-rai' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAl-Rai\M');
UPDATE public.products SET brand_id = 'brand-hajdu' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mHajdoo\M');
UPDATE public.products SET brand_id = 'brand-sunquick' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%سنكويك%');
UPDATE public.products SET brand_id = 'brand-al-arjawi' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mArjawi\M');
UPDATE public.products SET brand_id = 'brand-keraza' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mKaraza\M');
UPDATE public.products SET brand_id = 'brand-keraza' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mKeraza\M');
UPDATE public.products SET brand_id = 'brand-do-ghazal' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mDoğuş\M');
UPDATE public.products SET brand_id = 'brand-al-fakher' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%الفاخر%');
UPDATE public.products SET brand_id = 'brand-hamoul' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mHamoul\M');
UPDATE public.products SET brand_id = 'brand-al-kaseeh' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%الكسيح%');
UPDATE public.products SET brand_id = 'brand-somar' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mSummar\M');
UPDATE public.products SET brand_id = 'brand-aramis' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%أراميس%');
UPDATE public.products SET brand_id = 'brand-aramis' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAramis\M');
UPDATE public.products SET brand_id = 'brand-amarin' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%أمارين%');
UPDATE public.products SET brand_id = 'brand-amarin' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAmarin\M');
UPDATE public.products SET brand_id = 'brand-doctor-chef' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mDrChef\M');
UPDATE public.products SET brand_id = 'brand-hamada' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mHamada\M');
UPDATE public.products SET brand_id = 'brand-al-ghouta' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%الغوطة%');
UPDATE public.products SET brand_id = 'brand-yagouri' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%ياقوري%');
UPDATE public.products SET brand_id = 'brand-yagouri' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mYaguri\M');
UPDATE public.products SET brand_id = 'brand-najjar' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mNajjar\M');
UPDATE public.products SET brand_id = 'brand-kharta' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mKharta\M');
UPDATE public.products SET brand_id = 'brand-pepori' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%بيبوري%');
UPDATE public.products SET brand_id = 'brand-pepori' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mPepori\M');
UPDATE public.products SET brand_id = 'brand-pepori' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mBibori\M');
UPDATE public.products SET brand_id = 'brand-kalbahar' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%كلبهار%');
UPDATE public.products SET brand_id = 'brand-bulbul' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mBulbul\M');
UPDATE public.products SET brand_id = 'brand-shahia' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mShahia\M');
UPDATE public.products SET brand_id = 'brand-shahia' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mChahia\M');
UPDATE public.products SET brand_id = 'brand-alaska' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%الاسكا%');
UPDATE public.products SET brand_id = 'brand-alaska' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAlaska\M');
UPDATE public.products SET brand_id = 'brand-nabali' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mNabali\M');
UPDATE public.products SET brand_id = 'brand-afamia-al-sham' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAfamia\M');
UPDATE public.products SET brand_id = 'brand-nestle' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mNestle\M');
UPDATE public.products SET brand_id = 'brand-nestle' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mNestlé\M');
UPDATE public.products SET brand_id = 'brand-indomie' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%إندومي%');
UPDATE public.products SET brand_id = 'brand-indomie' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mIndomi\M');
UPDATE public.products SET brand_id = 'brand-aldurra' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%الدرة%');
UPDATE public.products SET brand_id = 'brand-aldurra' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mDurra\M');
UPDATE public.products SET brand_id = 'brand-shamsin' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%شمسين%');
UPDATE public.products SET brand_id = 'brand-derby' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%ديربي%');
UPDATE public.products SET brand_id = 'brand-derby' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mDerby\M');
UPDATE public.products SET brand_id = 'brand-laziza' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%لذيذة%');
UPDATE public.products SET brand_id = 'brand-al-rai' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mPicon\M');
UPDATE public.products SET brand_id = 'brand-al-rai' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAlrai\M');
UPDATE public.products SET brand_id = 'brand-hajdu' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%هاجدو%');
UPDATE public.products SET brand_id = 'brand-hajdu' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mHajdu\M');
UPDATE public.products SET brand_id = 'brand-vimto' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%فيمتو%');
UPDATE public.products SET brand_id = 'brand-vimto' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mVimto\M');
UPDATE public.products SET brand_id = 'brand-mahmoud' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])محمود([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-ahmad' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAhmad\M');
UPDATE public.products SET brand_id = 'brand-ahmad' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mAhmed\M');
UPDATE public.products SET brand_id = 'brand-hamoul' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])هامول([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-somar' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])سومار([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-somar' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mSomar\M');
UPDATE public.products SET brand_id = 'brand-hamada' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%حمادة%');
UPDATE public.products SET brand_id = 'brand-najjar' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mNajar\M');
UPDATE public.products SET brand_id = 'brand-kharta' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%خارطة%');
UPDATE public.products SET brand_id = 'brand-tosca' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])توسكا([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-tosca' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mTosca\M');
UPDATE public.products SET brand_id = 'brand-wazza-rice' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mWazza\M');
UPDATE public.products SET brand_id = 'brand-nabali' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%نبالي%');
UPDATE public.products SET brand_id = 'brand-chtoura-garden' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%شتورة%');
UPDATE public.products SET brand_id = 'brand-freshly' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%فرشلي%');
UPDATE public.products SET brand_id = 'brand-domo' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])دومو([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-domo' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mDomo\M');
UPDATE public.products SET brand_id = 'brand-lina' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])لينا([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-lina' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mLina\M');
UPDATE public.products SET brand_id = 'brand-shockx' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])شوكس([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-rani' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])راني([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-rani' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mRani\M');
UPDATE public.products SET brand_id = 'brand-dana' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])دانا([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-dana' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])دانة([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-dana' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mDana\M');
UPDATE public.products SET brand_id = 'brand-lara' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])لارا([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-lara' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mLara\M');
UPDATE public.products SET brand_id = 'brand-kiri' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])كيري([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-kiri' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mKiri\M');
UPDATE public.products SET brand_id = 'brand-puck' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mPuck\M');
UPDATE public.products SET brand_id = 'brand-keraza' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])كرزة([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-ahmad' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])أحمد([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-maza' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])مازا([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-maza' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mMaza\M');
UPDATE public.products SET brand_id = 'brand-dimo' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])ديمو([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-dimo' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mDemo\M');
UPDATE public.products SET brand_id = 'brand-dimo' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mDimo\M');
UPDATE public.products SET brand_id = 'brand-najjar' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])نجار([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-zwan' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])زوان([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-zwan' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mZwan\M');
UPDATE public.products SET brand_id = 'brand-bulbul' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])بلبل([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-shahia' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])شهية([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-hana' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mHana\M');
UPDATE public.products SET brand_id = 'brand-nestle' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ILIKE '%نسلة%');
UPDATE public.products SET brand_id = 'brand-rana' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mRana\M');
UPDATE public.products SET brand_id = 'brand-aldurra' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])درة([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-puck' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])بوك([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-puck' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '\mBok\M');
UPDATE public.products SET brand_id = 'brand-hana' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])هنا([[:space:]]|$)');
UPDATE public.products SET brand_id = 'brand-rana' WHERE deleted_at IS NULL AND brand_id IS NULL AND (concat_ws(' ', coalesce(name_ar,''), coalesce(name_de,''), coalesce(description,''), coalesce(ingredients,''), coalesce(allergens,''), coalesce(custom_note,''), coalesce(barcode,''), coalesce(product_number,'')) ~* '(^|[[:space:]])رنا([[:space:]]|$)');
COMMIT;

-- SELECT count(*) FROM public.brand_logos; -- expect 71
-- SELECT brand_id, count(*) FROM public.products WHERE brand_id IS NOT NULL GROUP BY 1 ORDER BY 2 DESC;
